name: rick_and_morty
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dio: ^5.0.2 # http request permite interceptors
  pretty_dio_logger: ^1.3.1 # interceptor
  get_it: ^7.2.0 # di
  injectable: ^2.1.0 # di
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.1
  url_launcher: ^6.1.11
  device_preview: ^1.1.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.2
  go_router: ^8.2.0

dependency_overrides: 
  test_api: 0.4.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4 # di
  build_runner: ^2.3.3 # di
  mocktail: ^0.3.0
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true